version: '3'

services:
  myst:
    image: mysteriumnetwork/myst:latest
    container_name: myst
    ports:
      - "1194:1194/udp"
      - "4447:4447"
    volumes:
      - ./data:/var/lib/mysterium-node
    environment:
      - MYSTERIUM_TEQUILAPI_ADDRESS=0.0.0.0
      - MYSTERIUM_LOCATION_COUNTRY=US
      - MYSTERIUM_LOCATION_CITY=New York
      - MYSTERIUM_LOCATION_LATITUDE=40.730610
      - MYSTERIUM_LOCATION_LONGITUDE=-73.935242
      - MYSTERIUM_IDENTITY_PASSPHRASE=your_passphrase
    restart: always
